# Generated by Django 5.1.2 on 2024-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
    ]
