# Generated by Django 5.1.2 on 2024-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(null=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(null=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(null=True, upload_to="media"),
        ),
    ]
